In [1]:
!pip install pandas

In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn import preprocessing

In [3]:
df = pd.read_csv("Car Insurance.csv")

In [4]:
df

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

In [5]:
df.iloc[:, 1]

0     2.0
1     4.0
2    15.0
3    13.0
4     2.0
5     8.0
6     NaN
7    20.0
8    13.0
9     7.0
Name: Age, dtype: float64

In [6]:
df.iloc[1]

Make          Ford
Age            4.0
Mileage    30500.0
Fuel             P
Gearbox          M
Colour       Black
Claimed        Yes
Name: 1, dtype: object

In [7]:
df['Colour']

0      Red
1    Black
2    White
3    White
4    Black
5    Green
6      NaN
7    Green
8     Blue
9    Black
Name: Colour, dtype: object

In [8]:
df

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

In [9]:
df.iloc[:,0].unique()

array(['Toyota', 'Ford', 'Nissan'], dtype=object)

In [10]:
df['Make'].unique()

array(['Toyota', 'Ford', 'Nissan'], dtype=object)

In [11]:
df['Make'].value_counts()

Toyota    4
Nissan    4
Ford      2
Name: Make, dtype: int64

In [12]:
df['Make'].isin(['Nissan'])

0    False
1    False
2    False
3     True
4     True
5    False
6    False
7     True
8    False
9     True
Name: Make, dtype: bool

In [13]:
df['Age'].sort_values()

0     2.0
4     2.0
1     4.0
9     7.0
5     8.0
3    13.0
8    13.0
2    15.0
7    20.0
6     NaN
Name: Age, dtype: float64

In [14]:
df['Age'].sort_values(ascending=False)

7    20.0
2    15.0
3    13.0
8    13.0
5     8.0
9     7.0
1     4.0
0     2.0
4     2.0
6     NaN
Name: Age, dtype: float64

In [15]:
df

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

In [16]:
df['Age'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Age, dtype: bool

In [17]:
df['Age'].isnull().any()

True

In [18]:
df.Age

0     2.0
1     4.0
2    15.0
3    13.0
4     2.0
5     8.0
6     NaN
7    20.0
8    13.0
9     7.0
Name: Age, dtype: float64

In [19]:
df.iloc[5,:].isnull().any()

True

In [20]:
!pip install scikit-learn

In [21]:
df.isnull().sum()

Make       0
Age        1
Mileage    1
Fuel       1
Gearbox    1
Colour     1
Claimed    0
dtype: int64

In [22]:
df

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

Data Preprocessing: Treating Missing Values for both numerical and categorical data in the table above

In [23]:
numImputer = SimpleImputer(missing_values=np.nan, strategy='mean')
numImputer = numImputer.fit(df[['Age', 'Mileage']])
df[['Age', 'Mileage']] = numImputer.transform(df[['Age', 'Mileage']])
catImputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
catImputer = catImputer.fit(df[['Fuel', 'Gearbox', 'Colour']])
df[['Fuel', 'Gearbox', 'Colour']] = catImputer.transform(df[['Fuel', 'Gearbox', 'Colour']])
df

Make        Age        Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.000000   27000.000000    P       A    Red     Yes
1    Ford   4.000000   30500.000000    P       M  Black     Yes
2  Toyota  15.000000  120000.000000    D       A  White      No
3  Nissan  13.000000   53000.000000    D       M  White      No
4  Nissan   2.000000   64722.222222    D       M  Black      No
5    Ford   8.000000   73000.000000    D       M  Green      No
6  Toyota   9.333333  138000.000000    P       M  Black     Yes
7  Nissan  20.000000   38000.000000    D       M  Green     Yes
8  Toyota  13.000000   67000.000000    D       A   Blue      No
9  Nissan   7.000000   36000.000000    P       M  Black     Yes

Line 24 to 28 explains, converting categorical data Field, that can take two or more possibele values using OneHotEncoder()
The categorical variables in each column are arranged alphabetically, and forms new column header

In [24]:
enc = preprocessing.OneHotEncoder()
enc.fit_transform(df[['Make', 'Fuel', 'Gearbox', 'Colour', 'Claimed']]). toarray()

array([[0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0.],
       [0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1.]])

The 'drop = first', is used to drop the first variable in each column after arranging alphabetically

In [25]:
enc = preprocessing.OneHotEncoder(drop = 'first')
enc.fit_transform(df[['Make', 'Fuel', 'Gearbox', 'Colour', 'Claimed']]). toarray()

array([[0., 1., 1., 0., 0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 1., 0., 0., 0., 0., 1.]])

In [26]:
enc.categories_

[array(['Ford', 'Nissan', 'Toyota'], dtype=object),
 array(['D', 'P'], dtype=object),
 array(['A', 'M'], dtype=object),
 array(['Black', 'Blue', 'Green', 'Red', 'White'], dtype=object),
 array(['No', 'Yes'], dtype=object)]

Explanation of converting categorical data Field, that can take only two values using OneHotEncoder()

In [27]:
enc = preprocessing.OrdinalEncoder()
enc.fit_transform(df['Claimed'].values.reshape(-1,1))

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.]])

In [28]:
enc.categories_

[array(['No', 'Yes'], dtype=object)]

Continuing from line 23, we have to convert the categorical variables to numerical variables of ('0' and '1') using
OrdinalEncoder and OneHotEncoder

In [29]:
enc = preprocessing.OrdinalEncoder()
df['Claimed'] = enc.fit_transform(df['Claimed'].values.reshape(-1,1))

enc = preprocessing.OneHotEncoder(drop = 'first')
onehots = enc.fit_transform(df[['Make', 'Fuel', 'Gearbox', 'Colour']]). toarray()

# Creating the new df

cols = []
for i in enc.categories_:
    i = np.delete(i,0)
    cols.extend(i)
df = df.join(pd.DataFrame(onehots, columns = cols))

df = df.drop(['Make', 'Fuel', 'Gearbox', 'Colour'], axis = 1)
df

Age        Mileage  Claimed  Nissan  Toyota    P    M  Blue  Green  \
0   2.000000   27000.000000      1.0     0.0     1.0  1.0  0.0   0.0    0.0   
1   4.000000   30500.000000      1.0     0.0     0.0  1.0  1.0   0.0    0.0   
2  15.000000  120000.000000      0.0     0.0     1.0  0.0  0.0   0.0    0.0   
3  13.000000   53000.000000      0.0     1.0     0.0  0.0  1.0   0.0    0.0   
4   2.000000   64722.222222      0.0     1.0     0.0  0.0  1.0   0.0    0.0   
5   8.000000   73000.000000      0.0     0.0     0.0  0.0  1.0   0.0    1.0   
6   9.333333  138000.000000      1.0     0.0     1.0  1.0  1.0   0.0    0.0   
7  20.000000   38000.000000      1.0     1.0     0.0  0.0  1.0   0.0    1.0   
8  13.000000   67000.000000      0.0     0.0     1.0  0.0  0.0   1.0    0.0   
9   7.000000   36000.000000      1.0     1.0     0.0  1.0  1.0   0.0    0.0   

   Red  White  
0  1.0    0.0  
1  0.0    0.0  
2  0.0    1.0  
3  0.0    1.0  
4  0.0    0.0  
5  0.0    0.0  
6  0.0    0.0  
7  0.0    0.0  
8  0.0    0.0  
9  0.0    0.0

Standardization of the data: This is because the variables are not on the same intervals, some values are large while
others are small hence we need to standardized the data using "StandardScaler()" or "MinMaxScaler()"

In [30]:
from sklearn import preprocessing

X = df.iloc[:,: -1].values
Y = df.iloc[:, -1].values

Method 1: Using "StandardScaler()"

In [31]:
scaler = preprocessing.StandardScaler().fit(X)

In [32]:
scaler.mean_

array([9.33333333e+00, 6.47222222e+04, 5.00000000e-01, 4.00000000e-01,
       4.00000000e-01, 4.00000000e-01, 7.00000000e-01, 1.00000000e-01,
       2.00000000e-01, 1.00000000e-01])

In [33]:
scaler.scale_

array([5.62138773e+00, 3.57345149e+04, 5.00000000e-01, 4.89897949e-01,
       4.89897949e-01, 4.89897949e-01, 4.58257569e-01, 3.00000000e-01,
       4.00000000e-01, 3.00000000e-01])

In [34]:
X_scaled = scaler.transform(X)
X_scaled

array([[-1.30454146e+00, -1.05562430e+00,  1.00000000e+00,
        -8.16496581e-01,  1.22474487e+00,  1.22474487e+00,
        -1.52752523e+00, -3.33333333e-01, -5.00000000e-01,
         3.00000000e+00],
       [-9.48757423e-01, -9.57679776e-01,  1.00000000e+00,
        -8.16496581e-01, -8.16496581e-01,  1.22474487e+00,
         6.54653671e-01, -3.33333333e-01, -5.00000000e-01,
        -3.33333333e-01],
       [ 1.00805476e+00,  1.54690159e+00, -1.00000000e+00,
        -8.16496581e-01,  1.22474487e+00, -8.16496581e-01,
        -1.52752523e+00, -3.33333333e-01, -5.00000000e-01,
        -3.33333333e-01],
       [ 6.52270728e-01, -3.28036417e-01, -1.00000000e+00,
         1.22474487e+00, -8.16496581e-01, -8.16496581e-01,
         6.54653671e-01, -3.33333333e-01, -5.00000000e-01,
        -3.33333333e-01],
       [-1.30454146e+00, -2.03611484e-16, -1.00000000e+00,
         1.22474487e+00, -8.16496581e-01, -8.16496581e-01,
         6.54653671e-01, -3.33333333e-01, -5.00000000e-01,
        -3.

Method 2: An alternative standardization is scaling features to lie between a given minimum and maximum value, often between zero and one, or so that the maximum absolute value of each feature is scaled to unit size. This can be achieved using MinMaxScaler.

In [35]:
min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X)
X_minmax

array([[0.        , 0.        , 1.        , 0.        , 1.        ,
        1.        , 0.        , 0.        , 0.        , 1.        ],
       [0.11111111, 0.03153153, 1.        , 0.        , 0.        ,
        1.        , 1.        , 0.        , 0.        , 0.        ],
       [0.72222222, 0.83783784, 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.61111111, 0.23423423, 0.        , 1.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.33983984, 0.        , 1.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.33333333, 0.41441441, 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 1.        , 0.        ],
       [0.40740741, 1.        , 1.        , 0.        , 1.        ,
        1.        , 1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.0990991 , 1.       